default_stages: [pre-commit, pre-push]

exclude: |
    (?x)(
        ^tests/fixtures/|
        ^ai_artifacts/|
        ^.claude/
    )

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: end-of-file-fixer
    -   id: check-ast

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
