version: '3.8'

services:
  test_py310:
    image: python:3.10-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      pytest -vvvv --color=yes --junit-xml=junit.xml --cov=pycaption --cov-report xml:coverage.xml;
      "
    volumes:
      - .:/pycaption

  test_py311:
    image: python:3.11-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      pytest -vvvv --color=yes --junit-xml=junit.xml --cov=pycaption --cov-report xml:coverage.xml;
      "
    volumes:
      - .:/pycaption

  test_py312:
    image: python:3.12-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      pytest -vvvv --color=yes --junit-xml=junit.xml --cov=pycaption --cov-report xml:coverage.xml;
      "
    volumes:
      - .:/pycaption