# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish PyCaption to PyPI

on: workflow_dispatch

jobs:
  call-unit-tests-workflow:
    name: Run unit tests
    uses: ana-nichifor/pycaption-test/.github/workflows/main.yml@main
#    uses: pbs/pycaption/.github/workflows/main.yml@main

  build-n-publish:
    name: Build and publish PyCaption to PyPI
#    needs: call-unit-tests-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m pip install --upgrade twine

    - name: Build package
      run: python -m build
      timeout-minutes: 10

    - name: Publish package on PyPI
      run: python3 -m twine upload --repository testpypi --verbose dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
